---
hostname : Leaf2
cli :
    host : "{{ ansible_host }}"
    username : admin
    password : Dell!234
    authorize : yes
    auth_pass : false
    transport : cli
intface : TenGigabitEthernet 1/19
